name: Build Flutter Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. نسخ ملفات المشروع من مستودعك
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. تثبيت بيئة الجافا المطلوبة للأندرويد
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # 3. تحميل وتثبيت بيئة Flutter الرسمية في السيرفر
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'

    # 4. تحميل المكتبات البرمجية المعتمدة والتأكد من سلامة المشروع
    - name: Install dependencies
      run: flutter pub get

    # 5. طبخ وبناء ملف الـ APK الاحترافي عالي السلاسة
    - name: Build APK
      run: flutter build apk --debug

    # 6. رفع ملف الـ APK الناتج لتحميله على هاتفك
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Flutter-Drawing-App
        path: build/app/outputs/flutter-apk/app-debug.apk
